TYPE = 0
MESSAGE_BODY = 1

MESSAGE = "1"
DELTA_OF_DEVICE = "2"
CHANGE_MASTER = "3"
GET_FROM_MASTER = "4"
SENSOR_NOT_CONNECTED = "5"
SAMPLES_MESSAGE ="2"

TRANSFER_FILE = "log"
MESSAGE_QUEUE_FILE = "message_queue"
TIME_TO_UPDATE = 60 #sec
BUFFER="[*********}"

TCP_PORT = 5005
B_SIZE = 2048
